name: GithubActionCheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        iteration: [1]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      
      - name: Read flavors from JSON and get first package name
        run: |
            ls -R
            flavorsJson=$(cat flavors.json)
            flavors=$(echo "$flavorsJson" | jq '.flavors')
            first_package_name=$(echo "$flavors" | jq -r '.[0].packageName')
            echo "The first package name is: $first_package_name"

          
        

      - name: Run Python script
        run: |
          echo "Running iteration ${{ matrix.iteration }}"
          python HelloWorld.py 
