name: Build and Release Workflow

on:
  push:
    branches:
      - main

jobs:
  setup_java:
    name: Set up Java and Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
    
       

  build_info_extractor:
    name: Extract Package Names
    runs-on: ubuntu-latest

    outputs:
      packageNames: ${{ steps.extract_packageNames.outputs.packageNames }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Package Names
        id: extract_packageNames
        run: |
          flavorsJson=$(cat flavors.json)
          packageNames=$(echo "$flavorsJson" | jq -r '.flavors[].packageName')
          echo "::set-output name=packageNames::$packageNames"

  sign_and_release:
    name: Sign and Release Bundles
    runs-on: ubuntu-latest
    needs: 
      - build_info_extractor
      - setup_java

    strategy:
      matrix:
        packageName: ${{needs.build_info_extractor.outputs.packageNames}}

    steps:
   
      - name: Sign AAB
        id: sign        
        uses: r0adkll/sign-android-release@v1         
        with:
            releaseDirectory: app/build/outputs/bundle/release       
            signingKeyBase64: ${{ secrets.SIGNING_KEY }}      
            alias: ${{ secrets.ALIAS }}   
            keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
            keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Release AAB
        id: release

        uses: r0adkll/upload-google-play@v1
        with:
            serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON}}
            packageName: ${{matrix.packageName}}
            releaseFile: ${{matrix.packageName}}debug/app-${{matrix.packageName}}-debug.aab
            track: qa
          


